version: '3.8'
services:
  php:
    build: './.docker/php/'
    ports: 
            - "8080:80"
            - "443:443"
    volumes:
      - ./www:/var/www/
      - ./.docker/apache/koding.men.conf:/etc/apache2/sites-enabled/koding.men.conf
      - ./.docker/apache/tuezy.dev.conf:/etc/apache2/sites-enabled/tuezy.dev.conf
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
    - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    - mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    volumes:
      - phpmyadmindata:/var/www/html
    ports:
      - '8081:80'

volumes:

  mysqldata:
  phpmyadmindata: